export CC	= gcc
export CFLAGS	= -Wall -ansi -pedantic
export BINARIES= mmu_manager oracle

SRC = src/

all:
	(cd $(SRC) && $(MAKE))

.PHONY: clean realclean

clean:
	(cd $(SRC) && $(MAKE) $@)

realclean:
	(cd $(SRC) && $(MAKE) $@)
